### ISSUE TITLE
Model files are temporarily unavailable

### ISSUE THREAD

**Issue by Shiva-CVML** [liuziwei7/fashion-landmarks#3]
Hi the model files are unavailable. Kindly inform when can they be available. Thanx

**Comment by liuziwei7** [comment]
Thanks for letting us know!

The model file downloading link is temporarily disabled due to large traffic. It should be resumed soon.

**Comment by vj-1988** [comment]
Would you be able to upload the files on google drive since they don't have any traffic restrictions? Dropbox seems to have 20gb/day restriction.

Thank you.

**Comment by liuziwei7** [comment]
Thanks for the information!

The model downloading links have been updated to Google Drive.

**Comment by vj-1988** [comment]
Thanks. The google drive link is working now. This issue can be closed.

**Comment by Shiva-CVML** [comment]
Thanx for uploading them on google drive. These models are very much useful for building our applications. I am closing the issue.
