### ISSUE TITLE
fc8 or fc8_softlabel?

### ISSUE THREAD

**Issue by vj-1988** [liuziwei7/fashion-landmarks#4]
Dear @liuziwei7 : I am currently converting the demo.m from matlab to python since I don't have matlab. I am currently using the output from 'fc8' layer after forwarding the image. But output from fc8 are in negative float values. Can you confirm if this is as expected.

**Comment by Shiva-CVML** [comment]
Hi vijay, i also need python script for my testing. Kindly share me the file if you could once you are done.

**Comment by yysijie** [comment]
Hi @vj-1988   
You can just use "fc8_landmarks" to get prediction of landmarks. "fc8" is the combination of landmarks and visibility. 
And fc8_landmarks has been normalized to [-0.5, 0.5], so I think that is not as expected.

**Comment by Shiva-CVML** [comment]
Hi @liuziwei7 : I have used fc8_landmarks to get the prediction of landmarks. But still i am getting negative values in the result.
Here is the result i got for one image on FLD_full model:
[[ 0.27906671  0.06566589 -0.00434459 -0.11829091  0.2226638   0.35514393
  -0.02583538  0.11681057  0.00701905  0.09816497  0.19388133  0.01659511
   0.22986662  0.01280492  0.30807292 -0.16883679]]
Any help will be appreciated. Thanks

**Comment by liuziwei7** [comment]
Actually "fc8_landmark" represents centered and normalized fashion landmark coordinates. 
Thus, the outputs of "fc8_landmark" are floats between [-0.5, 0.5], which could be either positive or negative.

Yes, the results you obtained are as expected. 
You can transform these floats into absolute coordinates by executing the inline function "get_orig_coordinate" (Line 35 in file "./scripts/pipeline_forward.m").

**Comment by Shiva-CVML** [comment]
I am getting the absolute coordinates, but those are not fitting for the input image. Are those coordinates obtained by that method corresponds to 224x224 resolution? Just clarify me on this.

**Comment by liuziwei7** [comment]
Yes, the obtained absolute coordinates are relative to input image with size of 224*224.

**Comment by Shiva-CVML** [comment]
Hi @liuziwei7 : Could you provide me the order of landmark points for full, upper and lower models? I am confused whether the first coordinate is for left arm or shoulder. I tried fitting with different combinations, but getting wrong landmarks. So just needed to verify whether i am fitting in wrong places? Thanks.

**Comment by liuziwei7** [comment]
The order of fashion landmarks is given in the README file of "Fashion Landmark Detection Benchmark": http://mmlab.ie.cuhk.edu.hk/projects/DeepFashion/LandmarkDetection.html . It should be: "left collar [x, y]", "right collar [x, y]", "left sleeve [x, y]", "right sleeve [x, y]", "left hemline [x, y]", "right hemline [x, y]".
