### ISSUE TITLE
CelebA dataset query

### ISSUE THREAD

**Issue by firestonelib** [liuziwei7/fashion-landmarks#5]
Dear liu,
           when I use the famous dataset CelebA, I found a problem: the location in list_bbox_celeba.txt is wrong, it does not fit the face. hope you will see my issue and tell me why this happened. waiting for you.

https://pan.baidu.com/s/1eSNpdRG#list/path=%2F

Best wishes

**Comment by liuziwei7** [comment]
Please send inquiries regarding CelebA to my email (lz013@ie.cuhk.edu.hk). Closing this for now.

**Comment by ycsun19** [comment]
Hi, have you solved the bbox error yet? What's more, there are several landmark error in list_landmarks_celeba.txt. @Designbook1
